# Generated by Django 4.1.4 on 2022-12-25 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254, verbose_name='Client Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100, verbose_name='Street Name')),
                ('street_number', models.CharField(max_length=10, verbose_name='Street Number')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Zip Code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.client')),
            ],
        ),
    ]
